language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'iojs'
  - '7'
  - '6'
  - '4'
before_script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = 6 ]; then export DISPLAY=:99.0; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = 6 ]; then sh -e /etc/init.d/xvfb start; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = 6 ]; then sleep 3; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${KARMA-}" ]; then npm run tests-karma ; fi'
after_success:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then npm run cover; cat ./coverage/lcov.info | ./node_modules/.bin/coveralls ; fi'
  - npm run semantic-release
env:
  global:
    - REACT=0.14
  matrix:
    - TEST=true
sudo: false
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
  allow_failures:
    - node_js: "iojs"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
